# Generated by Django 4.2.1 on 2023-06-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="tag",
            field=models.ManyToManyField(
                null=True, to="product.tag", verbose_name="tag_list"
            ),
        ),
    ]
