# Generated by Django 4.2.1 on 2023-05-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_type_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='title',
        ),
        migrations.AddField(
            model_name='blog',
            name='title_blog',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
